import "../globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montsernat = Montserrat({
   weight: ["400", "500", "600", "700", "800", "900"],
   subsets: ["latin"],
   display: "swap",
   fallback: ["Helvetica", "Arial", "sans-serif"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

interface Props {
   children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
   return (
      <html lang="en">
         <body className={montsernat.className}>{children}</body>
      </html>
   );
}
